apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gouz
  description: An example of a Backstage application.
  annotations:
    backstage.io/adr-location: adrs
spec:
  type: website
  owner: group:zenika
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: zenika
  description: The main group
spec:
  type: business-unit
  profile:
    displayName: Zenika
    email: infrastructure@example.com
    picture: https://training.zenika.com/_nuxt/img/zenika_logo_horizontal_black.a41f832.png
  children: [g-squad, backstage]
  members: [gouz]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: g-squad
  description: A task force team
spec:
  type: business-unit
  profile:
    displayName: G-Squad
    email: infrastructure@example.com
    picture: https://training.zenika.com/_nuxt/img/zenika_logo_horizontal_black.a41f832.png
  parent: zenika
  members: [gouz]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage
  description: The backstage team of zenika
spec:
  type: business-unit
  profile:
    displayName: Zenika/Backstage
    email: infrastructure@example.com
    picture: https://training.zenika.com/_nuxt/img/zenika_logo_horizontal_black.a41f832.png
  parent: zenika
  members: [gouz]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: gouz
spec:
  profile:
    displayName: Sylvain Gougouzian
    email: jenny-doe@example.com
    picture: https://sylvain.gougouzian.fr/me.jpg
  memberOf: [g-squad, zenika]
